let dataMovie = [
    {
        id:'1',
        name:'Lật Mặt 7: Một Điều Ước',
        gen:'Hài, Gia Đình',
        author:'Lý Hải',
        img:'./img/lat-mat-7.jpg',
        movieGen:'Phim Rạp',
        listMoive:'yes',
        popularMovie:'yes',
        Episodes:'1h30',
        rate: 9
    },
    {
        id:'2',
        name:'Em chưa 18+',
        gen:'Hài, Học Đường',
        author:'Lê Thanh Sơn',
        img:'./img/Em chưa 18.jpg',
        movieGen:'Phim Rạp',
        listMoive:'yes',
        popularMovie:'yes',
        Episodes:'1h21',
        rate: 8.9
    },
    {
        id:'3',
        name:'Cây Táo Nở Hoa',
        gen:'Tình Cảm, Gia Đình',
        author:'Võ Thạch Thảo',
        img:'./img/CTNH01.jpg"',
        movieGen:'Phim Dài Tập',
        listMoive:'yes',
        popularMovie:'yes',
        Episodes:'71',
        rate: 8.4
    },
    {
        id:'4',
        name:'Mai',
        gen:'Hài, Tình Cảm',
        author:'Trấn Thành',
        img:'./img/Mai.png',
        movieGen:'Phim Rạp',
        listMoive:'yes',
        popularMovie:'yes',
        Episodes:'1h35',
        rate: 9.2
    },
    {
        id:'5',
        name:'Averger',
        gen:'Hài, Hành Động',
        author:'Joss Whedon',
        img:'./img/Avengers.jpg',
        movieGen:'Phim Nước Ngoài',
        listMoive:'yes',
        popularMovie:'yes',
        Episodes:'1h50',
        rate: 9.6
    },
    {
        id:'6',
        name:'Tết Ở Làng Địa Ngục',
        gen:'Hài, Kinh Dị',
        author:'Trần Hữu Tấn',
        img:'./img/TOLDN.jpg',
        movieGen:'Phim Dài Tập',
        listMoive:'yes',
        popularMovie:'no',
        Episodes:'12',
        rate: 9.5
    },
    {
        id:'7',
        name:'Gạo Nếp Gạo Tẻ',
        gen:'Hài, Gia Đình',
        author:'Võ Thạch Thảo',
        img:'./img/Gaonepgaote.jpg',
        movieGen:'Phim Dài Tập',
        listMoive:'yes',
        popularMovie:'no',
        Episodes:'109',
        rate: 9.5
    },
    {
        id:'8',
        name:'Về Nhà Đi Con',
        gen:'Tình Cảm, Gia Đình',
        author:'Võ Thạch Thảo',
        img:'./img/VeNhaDiCon.webp',
        movieGen:'Phim Dài Tập',
        listMoive:'yes',
        popularMovie:'no',
        Episodes:'45',
        rate: 9.5
    },
    {
        id:'9',
        name:'Người Phán Xử',
        gen:'Hành Động',
        author:'Võ Thạch Thảo',
        img:'./img/NguoiPhanXu.jpg',
        movieGen:'Phim Dài Tập',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'47',
        rate: 9.5
    },
    {
        id:'10',
        name:'Quỳnh Búp bê',
        gen:'Gia Đình',
        author:'Võ Thạch Thảo',
        img:'./img/QuynhBupBe.jpg',
        movieGen:'Phim Dài Tập',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'49',
        rate: 9.5
    },
    {
        id:'11',
        name:'Sống Chung Với Mẹ Chồng',
        gen:'Gia Đình',
        author:'Võ Thạch Thảo',
        img:'./img/SongChungVoiMeChong.jpg',
        movieGen:'Phim Dài Tập',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'88',
        rate: 9.5
    },
    {
        id:'12',
        name:'Kính Vạn Hoa',
        gen:'Thiếu Nhi, Hài',
        author:'Võ Thạch Thảo',
        img:'./img/KinhVanHoa.jpg',
        movieGen:'Phim Dài Tập',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'20',
        rate: 9.5
    },
    {
        id:'13',
        name:'Bỗng Dưng Muốn Khóc',
        gen:'Hài, Tình Cảm',
        author:'Võ Thạch Thảo',
        img:'./img/BongDungMuonKhoc.webp',
        movieGen:'Phim Dài Tập',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'40',
        rate: 9.9
    },
    {
        id:'14',
        name:'Cổng Mặt Trời',
        gen:'Hài, Tình Cảm',
        author:'Võ Thạch Thảo',
        img:'./img/CongMatTroi.jpg',
        movieGen:'Phim Dài Tập',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'48',
        rate: 9
    },
    {
        id:'15',
        name:'Nắng',
        gen:'Hài, Tình Cảm',
        author:'Võ Thạch Thảo',
        img:'./img/Nang.jpg',
        movieGen:'Phim Rạp',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'1h30',
        rate: 9
    },
    {
        id:'16',
        name:'Tiệc Trăng máu',
        gen:'Hài, Tình Cảm',
        author:'Võ Thạch Thảo',
        img:'./img/TiecTrangMau.jpg',
        movieGen:'Phim Rạp',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'1h35',
        rate: 9.3
    },
    {
        id:'17',
        name:'Cua Lại Vợ Bầu',
        gen:'Hài, Tình Cảm',
        author:'Võ Thạch Thảo',
        img:'./img/CuaLaiVoBau.jfif',
        movieGen:'Phim Rạp',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'1h45',
        rate: 9.3
    },
    {
        id:'18',
        name:'Mắt Biếc',
        gen:'Hài, Tình Cảm',
        author:'Võ Thạch Thảo',
        img:'./img/MatBiec.jpg',
        movieGen:'Phim Rạp',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'1h55',
        rate: 9.7
    },
    {
        id:'19',
        name:'Tèo Em',
        gen:'Hài, Gia Đình',
        author:'Võ Thạch Thảo',
        img:'./img/TeoEm.jpg',
        movieGen:'Phim Rạp',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'1h55',
        rate: 9.7
    },
    {
        id:'20',
        name:'Nhà Bà Nữ',
        gen:'Hài, Gia Đình',
        author:'Võ Thạch Thảo',
        img:'./img/NhaBaNu.jpg',
        movieGen:'Phim Rạp',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'1h45',
        rate: 9.4
    },
    {
        id:'21',
        name:'Biện Viện Ma',
        gen:'Hài, Kinh Dị',
        author:'Võ Thạch Thảo',
        img:'./img/BienVienMa.webp',
        movieGen:'Phim Rạp',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'2h15',
        rate: 9.1
    },
    {
        id:'22',
        name:'The conjuring 1',
        gen:' Kinh Dị',
        author:'Võ Thạch Thảo',
        img:'./img/poster022.jpg',
        movieGen:'Phim Nước Ngoài',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'2h15',
        rate: 9.1
    },
    {
        id:'23',
        name:'The conjuring 2',
        gen:' Kinh Dị',
        author:'Võ Thạch Thảo',
        img:'./img/poster023.jpg',
        movieGen:'Phim Nước Ngoài',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'2h25',
        rate: 9.2
    },
    {
        id:'24',
        name:'The conjuring 3',
        gen:' Kinh Dị',
        author:'Võ Thạch Thảo',
        img:'./img/poster024.jpg',
        movieGen:'Phim Nước Ngoài',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'2h25',
        rate: 9.3
    },
    {
        id:'25',
        name:'insidious 1',
        gen:' Kinh Dị',
        author:'Võ Thạch Thảo',
        img:'./img/poster025.jpg',
        movieGen:'Phim Nước Ngoài',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'2h15',
        rate: 9.4
    },
    {
        id:'26',
        name:'insidious 2',
        gen:' Kinh Dị',
        author:'Võ Thạch Thảo',
        img:'./img/poster026.jpg',
        movieGen:'Phim Nước Ngoài',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'2h45',
        rate: 9.6
    },
    {
        id:'27',
        name:'insidious 3',
        gen:' Kinh Dị',
        author:'Võ Thạch Thảo',
        img:'./img/poster027.jpg',
        movieGen:'Phim Nước Ngoài',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'2h55',
        rate: 9.7
    },
    {
        id:'28',
        name:'The conjuring 4',
        gen:' Kinh Dị',
        author:'Võ Thạch Thảo',
        img:'./img/poster028.jpg',
        movieGen:'Phim Nước Ngoài',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'2h25',
        rate: 9.6
    },
    {
        id:'23',
        name:'The conjuring 2',
        gen:' Kinh Dị',
        author:'Võ Thạch Thảo',
        img:'./img/poster023.jpg',
        movieGen:'Phim Nước Ngoài',
        listMoive:'no',
        popularMovie:'no',
        Episodes:'2h25',
        rate: 9.2
    },


]

export {dataMovie}